### ISSUE TITLE
Error if empty array

### ISSUE THREAD

**Issue by randvoid** [garrisonhh/ghh_json#2]
Hi,

Thank you for your great and useful json parser! It's super easy to use.

I've got an error when trying to parse a json object with an empty array. Example:

```c
    json_t json2;
    char *test = "{\"foo\":\"bar\",\"boo\":[]}";
    json_load(&json2, test);
```

Error:

```
JSON ERROR: unknown token, expected value.
     1 | {"foo":"bar","boo":[]}
       |     
```

Kind regards,

**Comment by garrisonhh** [comment]
Thanks so much! It's very cool to see people using my code!

The issue should be fixed, I simply wasn't checking for closing braces before checking for values in arrays and objects. I guess I never actually tested empty arrays or objects, which is kind of hilarious honestly. Let me know if any issue arises!

**Comment by randvoid** [comment]
Yeah it's a really cool and easy to use json library! Thank you for your time and the quick response.
